// Exercise library sourced from free-exercise-db (public domain / Unlicense),
// https://github.com/yuhonas/free-exercise-db — 873 exercises, grouped by
// muscle group. Powers autocomplete suggestions; a coach can still type
// anything custom that isn't in this list.
module.exports = {
  "Chest": [
    "Alternating Floor Press",
    "Around The Worlds",
    "Barbell Bench Press - Medium Grip",
    "Barbell Guillotine Bench Press",
    "Barbell Incline Bench Press - Medium Grip",
    "Behind Head Chest Stretch",
    "Bench Press - With Bands",
    "Bent-Arm Dumbbell Pullover",
    "Bodyweight Flyes",
    "Butterfly",
    "Cable Chest Press",
    "Cable Crossover",
    "Cable Iron Cross",
    "Chain Press",
    "Chest And Front Of Shoulder Stretch",
    "Chest Stretch on Stability Ball",
    "Clock Push-Up",
    "Cross Over - With Bands",
    "Decline Barbell Bench Press",
    "Decline Dumbbell Bench Press",
    "Decline Dumbbell Flyes",
    "Decline Push-Up",
    "Decline Smith Press",
    "Dips - Chest Version",
    "Dumbbell Bench Press",
    "Dumbbell Bench Press with Neutral Grip",
    "Dumbbell Flyes",
    "Dynamic Chest Stretch",
    "Elbows Back",
    "Extended Range One-Arm Kettlebell Floor Press",
    "Flat Bench Cable Flyes",
    "Front Raise And Pullover",
    "Hammer Grip Incline DB Bench Press",
    "Incline Cable Chest Press",
    "Incline Cable Flye",
    "Incline Dumbbell Bench With Palms Facing In",
    "Incline Dumbbell Flyes",
    "Incline Dumbbell Flyes - With A Twist",
    "Incline Dumbbell Press",
    "Incline Push-Up",
    "Incline Push-Up Medium",
    "Incline Push-Up Reverse Grip",
    "Incline Push-Up Wide",
    "Isometric Wipers",
    "Leg-Over Floor Press",
    "Leverage Chest Press",
    "Leverage Decline Chest Press",
    "Leverage Incline Chest Press",
    "Low Cable Crossover",
    "Machine Bench Press",
    "Neck Press",
    "One Arm Dumbbell Bench Press",
    "One-Arm Flat Bench Dumbbell Flye",
    "One-Arm Kettlebell Floor Press",
    "Plyo Kettlebell Pushups",
    "Push Up to Side Plank",
    "Push-Up Wide",
    "Push-Ups With Feet Elevated",
    "Push-Ups With Feet On An Exercise Ball",
    "Pushups",
    "Pushups (Close and Wide Hand Positions)",
    "Single-Arm Cable Crossover",
    "Single-Arm Push-Up",
    "Smith Machine Bench Press",
    "Smith Machine Decline Press",
    "Smith Machine Incline Bench Press",
    "Standing Cable Chest Press",
    "Straight-Arm Dumbbell Pullover",
    "Suspended Push-Up",
    "Svend Press",
    "Wide-Grip Barbell Bench Press",
    "Wide-Grip Decline Barbell Bench Press",
    "Wide-Grip Decline Barbell Pullover",
  ],
  "Back": [
    "Alternating Kettlebell Row",
    "Alternating Renegade Row",
    "Band Assisted Pull-Up",
    "Barbell Deadlift",
    "Barbell Shrug",
    "Barbell Shrug Behind The Back",
    "Bent Over Barbell Row",
    "Bent Over One-Arm Long Bar Row",
    "Bent Over Two-Arm Long Bar Row",
    "Bent Over Two-Dumbbell Row",
    "Bent Over Two-Dumbbell Row With Palms In",
    "Bent-Arm Barbell Pullover",
    "Bodyweight Mid Row",
    "Cable Incline Pushdown",
    "Cable Shrugs",
    "Calf-Machine Shoulder Shrug",
    "Cat Stretch",
    "Chair Lower Back Stretch",
    "Child's Pose",
    "Chin-Up",
    "Close-Grip Front Lat Pulldown",
    "Crossover Reverse Lunge",
    "Dancer's Stretch",
    "Deadlift with Bands",
    "Deadlift with Chains",
    "Deficit Deadlift",
    "Dumbbell Incline Row",
    "Dumbbell Shrug",
    "Dynamic Back Stretch",
    "Elevated Cable Rows",
    "Full Range-Of-Motion Lat Pulldown",
    "Gironda Sternum Chins",
    "Hug A Ball",
    "Hug Knees To Chest",
    "Hyperextensions (Back Extensions)",
    "Hyperextensions With No Hyperextension Bench",
    "Incline Bench Pull",
    "Inverted Row",
    "Inverted Row with Straps",
    "Kettlebell Sumo High Pull",
    "Kipping Muscle Up",
    "Kneeling High Pulley Row",
    "Kneeling Single-Arm High Pulley Row",
    "Latissimus Dorsi-SMR",
    "Leverage High Row",
    "Leverage Iso Row",
    "Leverage Shrug",
    "London Bridges",
    "Lower Back-SMR",
    "Lying Cambered Barbell Row",
    "Lying T-Bar Row",
    "Middle Back Shrug",
    "Middle Back Stretch",
    "Mixed Grip Chin",
    "Muscle Up",
    "One Arm Against Wall",
    "One Arm Chin-Up",
    "One Arm Lat Pulldown",
    "One Handed Hang",
    "One-Arm Dumbbell Row",
    "One-Arm Kettlebell Row",
    "One-Arm Long Bar Row",
    "Overhead Lat",
    "Pelvic Tilt Into Bridge",
    "Pullups",
    "Pyramid",
    "Rack Pull with Bands",
    "Rack Pulls",
    "Reverse Band Deadlift",
    "Reverse Grip Bent-Over Rows",
    "Rhomboids-SMR",
    "Rocky Pull-Ups/Pulldowns",
    "Rope Climb",
    "Rope Straight-Arm Pulldown",
    "Scapular Pull-Up",
    "Seated Cable Rows",
    "Seated Good Mornings",
    "Seated One-arm Cable Pulley Rows",
    "Shotgun Row",
    "Side To Side Chins",
    "Side-Lying Floor Stretch",
    "Sled Row",
    "Smith Machine Behind the Back Shrug",
    "Smith Machine Bent Over Row",
    "Smith Machine Upright Row",
    "Spinal Stretch",
    "Standing Dumbbell Upright Row",
    "Standing Pelvic Tilt",
    "Stiff Leg Barbell Good Morning",
    "Straight Bar Bench Mid Rows",
    "Straight-Arm Pulldown",
    "Superman",
    "Suspended Row",
    "T-Bar Row with Handle",
    "Two-Arm Kettlebell Row",
    "Underhand Cable Pulldowns",
    "Upper Back Stretch",
    "Upright Cable Row",
    "Upright Row - With Bands",
    "V-Bar Pulldown",
    "V-Bar Pullup",
    "Weighted Ball Hyperextension",
    "Weighted Pull Ups",
    "Wide-Grip Lat Pulldown",
    "Wide-Grip Pulldown Behind The Neck",
    "Wide-Grip Rear Pull-Up",
  ],
  "Shoulders": [
    "Alternating Cable Shoulder Press",
    "Alternating Deltoid Raise",
    "Alternating Kettlebell Press",
    "Anti-Gravity Press",
    "Arm Circles",
    "Arnold Dumbbell Press",
    "Back Flyes - With Bands",
    "Band Pull Apart",
    "Barbell Incline Shoulder Raise",
    "Barbell Rear Delt Row",
    "Barbell Shoulder Press",
    "Battling Ropes",
    "Bent Over Dumbbell Rear Delt Raise With Head On Bench",
    "Bent Over Low-Pulley Side Lateral",
    "Bradford/Rocky Presses",
    "Cable Internal Rotation",
    "Cable Rear Delt Fly",
    "Cable Rope Rear-Delt Rows",
    "Cable Seated Lateral Raise",
    "Cable Shoulder Press",
    "Car Drivers",
    "Chair Upper Body Stretch",
    "Clean and Press",
    "Cuban Press",
    "Double Kettlebell Jerk",
    "Double Kettlebell Push Press",
    "Double Kettlebell Snatch",
    "Dumbbell Incline Shoulder Raise",
    "Dumbbell Lying One-Arm Rear Lateral Raise",
    "Dumbbell Lying Rear Lateral Raise",
    "Dumbbell One-Arm Shoulder Press",
    "Dumbbell One-Arm Upright Row",
    "Dumbbell Raise",
    "Dumbbell Scaption",
    "Dumbbell Shoulder Press",
    "Elbow Circles",
    "External Rotation",
    "External Rotation with Band",
    "External Rotation with Cable",
    "Face Pull",
    "Front Cable Raise",
    "Front Dumbbell Raise",
    "Front Incline Dumbbell Raise",
    "Front Plate Raise",
    "Front Two-Dumbbell Raise",
    "Handstand Push-Ups",
    "Internal Rotation with Band",
    "Iron Cross",
    "Kettlebell Arnold Press",
    "Kettlebell Pirate Ships",
    "Kettlebell Seated Press",
    "Kettlebell Seesaw Press",
    "Kettlebell Thruster",
    "Kettlebell Turkish Get-Up (Lunge style)",
    "Kettlebell Turkish Get-Up (Squat style)",
    "Landmine Linear Jammer",
    "Lateral Raise - With Bands",
    "Leverage Shoulder Press",
    "Low Pulley Row To Neck",
    "Lying One-Arm Lateral Raise",
    "Lying Rear Delt Raise",
    "Machine Shoulder (Military) Press",
    "One-Arm Incline Lateral Raise",
    "One-Arm Kettlebell Clean and Jerk",
    "One-Arm Kettlebell Jerk",
    "One-Arm Kettlebell Military Press To The Side",
    "One-Arm Kettlebell Para Press",
    "One-Arm Kettlebell Push Press",
    "One-Arm Kettlebell Snatch",
    "One-Arm Kettlebell Split Jerk",
    "One-Arm Kettlebell Split Snatch",
    "One-Arm Side Laterals",
    "Power Partials",
    "Reverse Flyes",
    "Reverse Flyes With External Rotation",
    "Reverse Machine Flyes",
    "Round The World Shoulder Stretch",
    "Seated Barbell Military Press",
    "Seated Bent-Over Rear Delt Raise",
    "Seated Cable Shoulder Press",
    "Seated Dumbbell Press",
    "Seated Front Deltoid",
    "Seated Side Lateral Raise",
    "See-Saw Press (Alternating Side Press)",
    "Shoulder Circles",
    "Shoulder Press - With Bands",
    "Shoulder Raise",
    "Shoulder Stretch",
    "Side Lateral Raise",
    "Side Laterals to Front Raise",
    "Side Wrist Pull",
    "Single Dumbbell Raise",
    "Single-Arm Linear Jammer",
    "Sled Overhead Backward Walk",
    "Sled Reverse Flye",
    "Smith Incline Shoulder Raise",
    "Smith Machine One-Arm Upright Row",
    "Smith Machine Overhead Shoulder Press",
    "Standing Alternating Dumbbell Press",
    "Standing Barbell Press Behind Neck",
    "Standing Bradford Press",
    "Standing Dumbbell Press",
    "Standing Dumbbell Straight-Arm Front Delt Raise Above Head",
    "Standing Front Barbell Raise Over Head",
    "Standing Low-Pulley Deltoid Raise",
    "Standing Military Press",
    "Standing Palm-In One-Arm Dumbbell Press",
    "Standing Palms-In Dumbbell Press",
    "Straight Raises on Incline Bench",
    "Two-Arm Kettlebell Clean",
    "Two-Arm Kettlebell Jerk",
    "Two-Arm Kettlebell Military Press",
    "Upright Barbell Row",
    "Upward Stretch",
  ],
  "Biceps": [
    "Alternate Hammer Curl",
    "Alternate Incline Dumbbell Curl",
    "Barbell Curl",
    "Barbell Curls Lying Against An Incline",
    "Brachialis-SMR",
    "Cable Hammer Curls - Rope Attachment",
    "Cable Preacher Curl",
    "Close-Grip EZ Bar Curl",
    "Close-Grip EZ-Bar Curl with Band",
    "Close-Grip Standing Barbell Curl",
    "Concentration Curls",
    "Cross Body Hammer Curl",
    "Drag Curl",
    "Dumbbell Alternate Bicep Curl",
    "Dumbbell Bicep Curl",
    "Dumbbell Prone Incline Curl",
    "EZ-Bar Curl",
    "Flexor Incline Dumbbell Curls",
    "Hammer Curls",
    "High Cable Curls",
    "Incline Dumbbell Curl",
    "Incline Hammer Curls",
    "Incline Inner Biceps Curl",
    "Lying Cable Curl",
    "Lying Close-Grip Bar Curl On High Pulley",
    "Lying High Bench Barbell Curl",
    "Lying Supine Dumbbell Curl",
    "Machine Bicep Curl",
    "Machine Preacher Curls",
    "One Arm Dumbbell Preacher Curl",
    "Overhead Cable Curl",
    "Preacher Curl",
    "Preacher Hammer Dumbbell Curl",
    "Reverse Barbell Curl",
    "Reverse Barbell Preacher Curls",
    "Reverse Cable Curl",
    "Reverse Plate Curls",
    "Seated Biceps",
    "Seated Close-Grip Concentration Barbell Curl",
    "Seated Dumbbell Curl",
    "Seated Dumbbell Inner Biceps Curl",
    "Spider Curl",
    "Standing Biceps Cable Curl",
    "Standing Biceps Stretch",
    "Standing Concentration Curl",
    "Standing Dumbbell Reverse Curl",
    "Standing Inner-Biceps Curl",
    "Standing One-Arm Cable Curl",
    "Standing One-Arm Dumbbell Curl Over Incline Bench",
    "Two-Arm Dumbbell Preacher Curl",
    "Wide-Grip Standing Barbell Curl",
    "Zottman Curl",
    "Zottman Preacher Curl",
  ],
  "Triceps": [
    "Band Skull Crusher",
    "Bench Dips",
    "Bench Press - Powerlifting",
    "Bench Press with Chains",
    "Board Press",
    "Body Tricep Press",
    "Body-Up",
    "Cable Incline Triceps Extension",
    "Cable Lying Triceps Extension",
    "Cable One Arm Tricep Extension",
    "Cable Rope Overhead Triceps Extension",
    "Chain Handle Extension",
    "Close-Grip Barbell Bench Press",
    "Close-Grip Dumbbell Press",
    "Close-Grip EZ-Bar Press",
    "Close-Grip Push-Up off of a Dumbbell",
    "Decline Close-Grip Bench To Skull Crusher",
    "Decline Dumbbell Triceps Extension",
    "Decline EZ Bar Triceps Extension",
    "Dip Machine",
    "Dips - Triceps Version",
    "Dumbbell Floor Press",
    "Dumbbell One-Arm Triceps Extension",
    "Dumbbell Tricep Extension -Pronated Grip",
    "EZ-Bar Skullcrusher",
    "Floor Press",
    "Floor Press with Chains",
    "Incline Barbell Triceps Extension",
    "Incline Push-Up Close-Grip",
    "JM Press",
    "Kneeling Cable Triceps Extension",
    "Low Cable Triceps Extension",
    "Lying Close-Grip Barbell Triceps Extension Behind The Head",
    "Lying Close-Grip Barbell Triceps Press To Chin",
    "Lying Dumbbell Tricep Extension",
    "Lying Triceps Press",
    "Machine Triceps Extension",
    "One Arm Floor Press",
    "One Arm Pronated Dumbbell Triceps Extension",
    "One Arm Supinated Dumbbell Triceps Extension",
    "Overhead Triceps",
    "Parallel Bar Dip",
    "Pin Presses",
    "Push-Ups - Close Triceps Position",
    "Reverse Band Bench Press",
    "Reverse Grip Triceps Pushdown",
    "Reverse Triceps Bench Press",
    "Ring Dips",
    "Seated Bent-Over One-Arm Dumbbell Triceps Extension",
    "Seated Bent-Over Two-Arm Dumbbell Triceps Extension",
    "Seated Triceps Press",
    "Sled Overhead Triceps Extension",
    "Smith Machine Close-Grip Bench Press",
    "Speed Band Overhead Triceps",
    "Standing Bent-Over One-Arm Dumbbell Triceps Extension",
    "Standing Bent-Over Two-Arm Dumbbell Triceps Extension",
    "Standing Dumbbell Triceps Extension",
    "Standing Low-Pulley One-Arm Triceps Extension",
    "Standing One-Arm Dumbbell Triceps Extension",
    "Standing Overhead Barbell Triceps Extension",
    "Standing Towel Triceps Extension",
    "Tate Press",
    "Tricep Dumbbell Kickback",
    "Tricep Side Stretch",
    "Triceps Overhead Extension with Rope",
    "Triceps Pushdown",
    "Triceps Pushdown - Rope Attachment",
    "Triceps Pushdown - V-Bar Attachment",
    "Triceps Stretch",
    "Weighted Bench Dip",
  ],
  "Forearms": [
    "Bottoms-Up Clean From The Hang Position",
    "Cable Wrist Curl",
    "Dumbbell Lying Pronation",
    "Dumbbell Lying Supination",
    "Finger Curls",
    "Kneeling Forearm Stretch",
    "Palms-Down Dumbbell Wrist Curl Over A Bench",
    "Palms-Down Wrist Curl Over A Bench",
    "Palms-Up Barbell Wrist Curl Over A Bench",
    "Palms-Up Dumbbell Wrist Curl Over A Bench",
    "Plate Pinch",
    "Seated Dumbbell Palms-Down Wrist Curl",
    "Seated Dumbbell Palms-Up Wrist Curl",
    "Seated One-Arm Dumbbell Palms-Down Wrist Curl",
    "Seated One-Arm Dumbbell Palms-Up Wrist Curl",
    "Seated Palm-Up Barbell Wrist Curl",
    "Seated Palms-Down Barbell Wrist Curl",
    "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl",
    "Standing Olympic Plate Hand Squeeze",
    "Standing Palms-Up Barbell Behind The Back Wrist Curl",
    "Wrist Circles",
    "Wrist Roller",
    "Wrist Rotations with Straight Bar",
  ],
  "Quads": [
    "All Fours Quad Stretch",
    "Barbell Full Squat",
    "Barbell Hack Squat",
    "Barbell Lunge",
    "Barbell Side Split Squat",
    "Barbell Squat",
    "Barbell Squat To A Bench",
    "Barbell Step Ups",
    "Barbell Walking Lunge",
    "Bodyweight Squat",
    "Bodyweight Walking Lunge",
    "Box Squat",
    "Box Squat with Bands",
    "Box Squat with Chains",
    "Cable Deadlifts",
    "Cable Hip Adduction",
    "Chair Squat",
    "Dumbbell Lunges",
    "Dumbbell Rear Lunge",
    "Dumbbell Squat",
    "Dumbbell Squat To A Bench",
    "Dumbbell Step Ups",
    "Elevated Back Lunge",
    "Freehand Jump Squat",
    "Frog Hops",
    "Front Barbell Squat",
    "Front Barbell Squat To A Bench",
    "Front Squat (Clean Grip)",
    "Front Squats With Two Kettlebells",
    "Goblet Squat",
    "Hack Squat",
    "Hip Flexion with Band",
    "Intermediate Hip Flexor and Quad Stretch",
    "Iron Crosses (stretch)",
    "Jefferson Squats",
    "Kettlebell Pistol Squat",
    "Kneeling Hip Flexor",
    "Leg Extensions",
    "Leg Press",
    "Leverage Deadlift",
    "Looking At Ceiling",
    "Lunge Sprint",
    "Lying Machine Squat",
    "Lying Prone Quadriceps",
    "Narrow Stance Hack Squats",
    "Narrow Stance Leg Press",
    "Narrow Stance Squats",
    "On Your Side Quad Stretch",
    "On-Your-Back Quad Stretch",
    "One Half Locust",
    "One Leg Barbell Squat",
    "One-Arm Overhead Kettlebell Squats",
    "One-Arm Side Deadlift",
    "Plie Dumbbell Squat",
    "Quad Stretch",
    "Quadriceps-SMR",
    "Rear Leg Raises",
    "Reverse Band Box Squat",
    "Reverse Band Power Squat",
    "Single-Leg High Box Squat",
    "Single-Leg Leg Extension",
    "Sit Squats",
    "Smith Machine Leg Press",
    "Smith Machine Pistol Squat",
    "Smith Machine Squat",
    "Smith Single-Leg Split Squat",
    "Speed Box Squat",
    "Speed Squats",
    "Split Squat with Dumbbells",
    "Squat Jerk",
    "Squat with Bands",
    "Squat with Chains",
    "Squat with Plate Movers",
    "Squats - With Bands",
    "Standing Elevated Quad Stretch",
    "Standing Hip Flexors",
    "Suspended Split Squat",
    "Trap Bar Deadlift",
    "Weighted Jump Squat",
    "Weighted Sissy Squat",
    "Weighted Squat",
    "Wide Stance Barbell Squat",
    "Zercher Squats",
  ],
  "Hamstrings": [
    "90/90 Hamstring",
    "Alternating Hang Clean",
    "Ball Leg Curl",
    "Band Good Morning",
    "Band Good Morning (Pull Through)",
    "Chair Leg Extended Stretch",
    "Double Kettlebell Alternating Hang Clean",
    "Dumbbell Clean",
    "Floor Glute-Ham Raise",
    "Front Leg Raises",
    "Glute Ham Raise",
    "Good Morning",
    "Good Morning off Pins",
    "Hamstring Stretch",
    "Hamstring-SMR",
    "Hanging Bar Good Morning",
    "Inchworm",
    "Intermediate Groin Stretch",
    "Kettlebell Dead Clean",
    "Kettlebell Hang Clean",
    "Kettlebell One-Legged Deadlift",
    "Leg-Up Hamstring Stretch",
    "Lunge Pass Through",
    "Lying Hamstring",
    "Lying Leg Curls",
    "Natural Glute Ham Raise",
    "One-Arm Kettlebell Clean",
    "One-Arm Kettlebell Swings",
    "One-Arm Open Palm Kettlebell Clean",
    "Open Palm Kettlebell Clean",
    "Platform Hamstring Slides",
    "Power Clean",
    "Prone Manual Hamstring",
    "Reverse Band Sumo Deadlift",
    "Reverse Hyperextension",
    "Romanian Deadlift",
    "Runner's Stretch",
    "Seated Band Hamstring Curl",
    "Seated Floor Hamstring Stretch",
    "Seated Hamstring",
    "Seated Hamstring and Calf Stretch",
    "Seated Leg Curl",
    "Smith Machine Hang Power Clean",
    "Smith Machine Stiff-Legged Deadlift",
    "Snatch Pull",
    "Split Squats",
    "Standing Hamstring and Calf Stretch",
    "Standing Leg Curl",
    "Standing Toe Touches",
    "Stiff-Legged Barbell Deadlift",
    "Stiff-Legged Dumbbell Deadlift",
    "Sumo Deadlift",
    "Sumo Deadlift with Bands",
    "Sumo Deadlift with Chains",
    "The Straddle",
    "Upper Back-Leg Grab",
    "World's Greatest Stretch",
  ],
  "Glutes": [
    "Adductor",
    "Adductor/Groin",
    "Ankle On The Knee",
    "Band Hip Adductions",
    "Barbell Glute Bridge",
    "Barbell Hip Thrust",
    "Butt Lift (Bridge)",
    "Downward Facing Balance",
    "Flutter Kicks",
    "Glute Kickback",
    "Groin and Back Stretch",
    "Groiners",
    "Hip Circles (prone)",
    "Hip Extension with Bands",
    "Hip Lift with Band",
    "IT Band and Glute Stretch",
    "Iliotibial Tract-SMR",
    "Knee Across The Body",
    "Kneeling Squat",
    "Leg Lift",
    "Lying Bent Leg Groin",
    "Lying Crossover",
    "Lying Glute",
    "Monster Walk",
    "One Knee To Chest",
    "One-Legged Cable Kickback",
    "Physioball Hip Bridge",
    "Piriformis-SMR",
    "Pull Through",
    "Seated Glute",
    "Side Leg Raises",
    "Side Lying Groin Stretch",
    "Single Leg Glute Bridge",
    "Standing Hip Circles",
    "Step-up with Knee Raise",
    "Thigh Abductor",
    "Thigh Adductor",
    "Windmills",
  ],
  "Calves": [
    "Ankle Circles",
    "Anterior Tibialis-SMR",
    "Balance Board",
    "Barbell Seated Calf Raise",
    "Calf Press",
    "Calf Press On The Leg Press Machine",
    "Calf Raise On A Dumbbell",
    "Calf Raises - With Bands",
    "Calf Stretch Elbows Against Wall",
    "Calf Stretch Hands Against Wall",
    "Calves-SMR",
    "Donkey Calf Raises",
    "Dumbbell Seated One-Leg Calf Raise",
    "Foot-SMR",
    "Knee Circles",
    "Peroneals Stretch",
    "Peroneals-SMR",
    "Posterior Tibialis Stretch",
    "Rocking Standing Calf Raise",
    "Seated Calf Raise",
    "Seated Calf Stretch",
    "Smith Machine Calf Raise",
    "Smith Machine Reverse Calf Raises",
    "Standing Barbell Calf Raise",
    "Standing Calf Raises",
    "Standing Dumbbell Calf Raise",
    "Standing Gastrocnemius Calf Stretch",
    "Standing Soleus And Achilles Stretch",
  ],
  "Core": [
    "3/4 Sit-Up",
    "Ab Crunch Machine",
    "Ab Roller",
    "Advanced Kettlebell Windmill",
    "Air Bike",
    "Alternate Heel Touchers",
    "Barbell Ab Rollout",
    "Barbell Ab Rollout - On Knees",
    "Barbell Rollout from Bench",
    "Barbell Side Bend",
    "Bent Press",
    "Bent-Knee Hip Raise",
    "Bosu Ball Cable Crunch With Side Bends",
    "Bottoms Up",
    "Butt-Ups",
    "Cable Crunch",
    "Cable Judo Flip",
    "Cable Reverse Crunch",
    "Cable Russian Twists",
    "Cable Seated Crunch",
    "Cocoons",
    "Cross-Body Crunch",
    "Crunch - Hands Overhead",
    "Crunch - Legs On Exercise Ball",
    "Crunches",
    "Dead Bug",
    "Decline Crunch",
    "Decline Oblique Crunch",
    "Decline Reverse Crunch",
    "Double Kettlebell Windmill",
    "Dumbbell Side Bend",
    "Elbow to Knee",
    "Exercise Ball Crunch",
    "Exercise Ball Pull-In",
    "Flat Bench Leg Pull-In",
    "Flat Bench Lying Leg Raise",
    "Frog Sit-Ups",
    "Gorilla Chin/Crunch",
    "Hanging Leg Raise",
    "Hanging Pike",
    "Jackknife Sit-Up",
    "Janda Sit-Up",
    "Kettlebell Figure 8",
    "Kettlebell Pass Between The Legs",
    "Kettlebell Windmill",
    "Knee/Hip Raise On Parallel Bars",
    "Kneeling Cable Crunch With Alternating Oblique Twists",
    "Landmine 180's",
    "Leg Pull-In",
    "Lower Back Curl",
    "Oblique Crunches",
    "Oblique Crunches - On The Floor",
    "One-Arm High-Pulley Cable Side Bends",
    "One-Arm Medicine Ball Slam",
    "Otis-Up",
    "Overhead Stretch",
    "Pallof Press",
    "Pallof Press With Rotation",
    "Plank",
    "Plate Twist",
    "Press Sit-Up",
    "Reverse Crunch",
    "Rope Crunch",
    "Russian Twist",
    "Scissor Kick",
    "Seated Barbell Twist",
    "Seated Flat Bench Leg Pull-In",
    "Seated Leg Tucks",
    "Seated Overhead Stretch",
    "Side Bridge",
    "Side Jackknife",
    "Sit-Up",
    "Smith Machine Hip Raise",
    "Spell Caster",
    "Spider Crawl",
    "Standing Cable Lift",
    "Standing Cable Wood Chop",
    "Standing Lateral Stretch",
    "Standing Rope Crunch",
    "Stomach Vacuum",
    "Suspended Fallout",
    "Suspended Reverse Crunch",
    "Toe Touchers",
    "Torso Rotation",
    "Tuck Crunch",
    "Weighted Ball Side Bend",
    "Weighted Crunches",
    "Weighted Sit-Ups - With Bands",
    "Wind Sprints",
  ],
  "Full Body": [
    "Alternate Leg Diagonal Bound",
    "Atlas Stone Trainer",
    "Atlas Stones",
    "Axle Deadlift",
    "Backward Drag",
    "Backward Medicine Ball Throw",
    "Bear Crawl Sled Drags",
    "Bench Jump",
    "Bench Sprint",
    "Box Jump (Multiple Response)",
    "Box Skip",
    "Car Deadlift",
    "Carioca Quick Step",
    "Catch and Overhead Throw",
    "Chest Push (multiple response)",
    "Chest Push (single response)",
    "Chest Push from 3 point stance",
    "Chest Push with Run Release",
    "Chin To Chest Stretch",
    "Circus Bell",
    "Clean",
    "Clean Deadlift",
    "Clean Pull",
    "Clean Shrug",
    "Clean and Jerk",
    "Clean from Blocks",
    "Conan's Wheel",
    "Crucifix",
    "Depth Jump Leap",
    "Double Leg Butt Kick",
    "Drop Push",
    "Dumbbell Seated Box Jump",
    "Farmer's Walk",
    "Fast Skipping",
    "Forward Drag with Press",
    "Frankenstein Squat",
    "Front Box Jump",
    "Front Cone Hops (or hurdle hops)",
    "Hang Clean",
    "Hang Clean - Below the Knees",
    "Hang Snatch",
    "Hang Snatch - Below Knees",
    "Heaving Snatch Balance",
    "Heavy Bag Thrust",
    "Hurdle Hops",
    "Incline Push-Up Depth Jump",
    "Isometric Chest Squeezes",
    "Isometric Neck Exercise - Front And Back",
    "Isometric Neck Exercise - Sides",
    "Jerk Balance",
    "Jerk Dip Squat",
    "Keg Load",
    "Knee Tuck Jump",
    "Kneeling Arm Drill",
    "Kneeling Jump Squat",
    "Lateral Bound",
    "Lateral Box Jump",
    "Lateral Cone Hops",
    "Linear 3-Part Start Technique",
    "Linear Acceleration Wall Drill",
    "Linear Depth Jump",
    "Log Lift",
    "Lying Face Down Plate Neck Resistance",
    "Lying Face Up Plate Neck Resistance",
    "Medicine Ball Chest Pass",
    "Medicine Ball Full Twist",
    "Medicine Ball Scoop Throw",
    "Mountain Climbers",
    "Moving Claw Series",
    "Muscle Snatch",
    "Neck-SMR",
    "Olympic Squat",
    "Overhead Slam",
    "Overhead Squat",
    "Plyo Push-up",
    "Power Clean from Blocks",
    "Power Jerk",
    "Power Snatch",
    "Power Snatch from Blocks",
    "Power Stairs",
    "Push Press",
    "Push Press - Behind the Neck",
    "Quick Leap",
    "Rack Delivery",
    "Return Push from Stance",
    "Rickshaw Carry",
    "Rickshaw Deadlift",
    "Rocket Jump",
    "Romanian Deadlift from Deficit",
    "Sandbag Load",
    "Scissors Jump",
    "Seated Head Harness Neck Resistance",
    "Side Hop-Sprint",
    "Side Neck Stretch",
    "Side Standing Long Jump",
    "Side to Side Box Shuffle",
    "Single Leg Butt Kick",
    "Single Leg Push-off",
    "Single-Cone Sprint Drill",
    "Single-Leg Hop Progression",
    "Single-Leg Lateral Hop",
    "Single-Leg Stride Jump",
    "Sled Drag - Harness",
    "Sled Push",
    "Sledgehammer Swings",
    "Snatch",
    "Snatch Balance",
    "Snatch Deadlift",
    "Snatch Shrug",
    "Snatch from Blocks",
    "Split Clean",
    "Split Jerk",
    "Split Jump",
    "Split Snatch",
    "Standing Long Jump",
    "Standing Two-Arm Overhead Throw",
    "Star Jump",
    "Stride Jump Crossover",
    "Supine Chest Throw",
    "Supine One-Arm Overhead Throw",
    "Supine Two-Arm Overhead Throw",
    "Tire Flip",
    "Vertical Swing",
    "Wide Stance Stiff Legs",
    "Yoke Walk",
  ],
  "Cardio": [
    "Bicycling",
    "Bicycling, Stationary",
    "Elliptical Trainer",
    "Jogging, Treadmill",
    "Prowler Sprint",
    "Recumbent Bike",
    "Rope Jumping",
    "Rowing, Stationary",
    "Running, Treadmill",
    "Skating",
    "Stairmaster",
    "Step Mill",
    "Trail Running/Walking",
    "Walking, Treadmill",
  ],
};
